apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-3
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/brijendra-beehyv/argocd.git
    targetRevision: HEAD
    path: my-app/app-3

    helm:
      releaseName: my-helm-app
      valueFiles:
        - ./values.yaml
        - ../envs/dev/values.yaml
  
  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
