---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: foo
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: brijendrasingh0369/nginx:0.1.1
        ports:
        - containerPort: 80
